version: '3.8'

services:
  student-harry:
    image: harry-student-dev
    build: .
    container_name: student-harry
    ports:
      - "2222:22"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - /home/harry/OrgSync:/home/ubuntu/OrgSync
      - /home/harry/miniforge3:/home/ubuntu/miniforge3
    restart: unless-stopped
    runtime: nvidia
